name: doc-build

on:
  release:
    types:
      - published

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      shell: bash

    - name: docker pull
      run: docker pull node:13.7.0-alpine
      shell: bash

    - name: docker build
      run: docker build -t gha-test:test01 . --no-cache
      shell: bash

    - name: docker run
      run: docker run -d -p 3000:3000 gha-test

    - name: docker push
      run: docker push testdockngdev/gha-test:test01


